### ISSUE TITLE
Subscriptions/abonnement + events/hændelser

### ISSUE THREAD

**Issue by andersfausboll** [digst/sharing#11]
We need to address 'abonnement' and 'hændelser' irgendwo in das Dokument.

**Comment by madsh** [comment]
og det bliver som tillægs service til funktionen "datadistributør"

Se #25 og #30

**Comment by madsh** [comment]
Nu er der plads til at skrive om det... tilføjet som service og abonnement og begivenhed til forretningsobjekter.
