### ISSUE TITLE
Send link vs. send data

### ISSUE THREAD

**Issue by andersfausboll** [digst/sharing#14]
A typical pattern is for a user to send a link to data, This pattern is captured in the implementation patterns of v0.3. However, we should also capture the 'privacy by design' aspects of this pattern (i.e., data not sent in the message) and mention it somewhere in the document.

**Comment by madsh** [comment]
Præsenteres efter de to 'rene' processer og formuleres hybrid/alternativ variant.

**Comment by andersfausboll** [comment]
Added to document - closing issue. #
