### ISSUE TITLE
Streaming as sharing pattern?

### ISSUE THREAD

**Issue by andersfausboll** [digst/sharing#2]
We must decide whether 'streaming' (of video) should be introduced as data sharing pattern?

**Comment by madsh** [comment]
The solutions could be to share links and information about start and stop. If you store video, you should also be able to share.

**Comment by andersfausboll** [comment]
Should also consider IoT (surveillance, health monitoring etc.). And IHE.

**Comment by madsh** [comment]
Er uden for scope.... deling af media...

**Comment by andersfausboll** [comment]
Reopen. Fanges som en variant af 'Hent' (hent af data bid for bid).

**Comment by andersfausboll** [comment]
Closing issue. Adding to scope section:
_- Streaming af data (videodata, IoT-data m.m.) --> Out of scope

I forhold til streaming af data bemærkes det, at streaming løseligt kan beskrives som en seriel række af processen `videregivelse på forespørgsel`, som vi beskriver senere i dette dokument. Eventuelle, yderligere aspekter ved streaming, der kan være relevante at dykke ned i i referencearkitektursammenhæng, er ikke inkluderet i denne referencearkitektur, men må henvises til en specialiseret referencearkitektur for streaming af data._
