### ISSUE TITLE
Data user - direct or SOA access to data?

### ISSUE THREAD

**Issue by andersfausboll** [digst/sharing#7]
Uafklaret: Skal Dataanvenders applikationer/services have direkte adgang til distribuerede data, eller skal adgang fortsat ske via et servicesnit, der kan varetage adgangskontol m.m.? 

Cf. comment from Andres H.

**Comment by madsh** [comment]
In the last pattern there are missing a requirement (arrow) from the "sammenstilling" to the Log on the platform. Added in tutti

**Comment by madsh** [comment]
direkte adgang.
