### ISSUE TITLE
Should fully open data (no access restrictions) be covered?

### ISSUE THREAD

**Issue by andersfausboll** [digst/sharing#9]
Should fully open data (no access restrictions) be covered in the reference architecture? As of mid Oct. 2017, we list it as being out of scope.

**Comment by madsh** [comment]
Yes. Vi skriver lidt om at at API'er stadig skal beskyttes. Men at public cloud, hvor anvender betaler hele gildet kan være en mulighed.

**Comment by madsh** [comment]
Skal skrives ind i forbindelse med generaliseringen af use cases. 
Åbne grunddata fx CVR, navn, nummer og adresse. 
...
Særlige personfølsoimme helbredsdata

**Comment by andersfausboll** [comment]
Closing issue - added to 'vurder adgang': Slutteligt bemærkes, at særlige typer af data ikke er belagt med nogen adgangsrestriktioner og dermed er frit tilgængelige (fx CVR-data).
(which is a trivial case of enforcing access restrictions)
